### ISSUE TITLE
Make bet page great (again)

### ISSUE THREAD

**Issue by mcepok** [teheru/nczone#22]
* The bet page is missing the sort functions like the player list
* The current default sort criteria is (bets won + 1) / (bets lost + 1), but the values are too high for this to work (it's actually the same as just the bets won rate)
  * Think of something else to sort for or just don't show players with too few bets

**Comment by Des-** [comment]
Is this still up-to-date? Why do we need to change the sorting?

However, maybe we can sort for something like the following:
bets won *3 - bets lost *2

Additionally, we could consider only counting the bets of the last 6 months. This could generate more competition. However, I assume that no one really cares about the bet-statistics atm since bets do not influence anything in the nC-zone.

**Comment by Zutatensuppe** [comment]
Bets are now sortable (sort is switchable like on players table). Default sort is the quota.

**Comment by Zutatensuppe** [comment]
have added the sorting stuff, default sort by rate, can be sorted like the players list. is this ticket resolved?

**Comment by mcepok** [comment]
@Zutatensuppe Since the players having like 2 bets won and 2 bets in total will always be place one, I'd rather have another field which we use as default order. Des proposal bets_won*3 - bets_list*2 sounds like a good idea. Maybe add another column with that value and use it by default.

**Comment by Zutatensuppe** [comment]
I named the new column "Wettskill" or "bet skill" xD
